name: Project CI/CD Pipeline

# --- Triggers ---
# This workflow runs on pushes and pull requests targeting the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
jobs:
  # Job 1: Run code quality checks and unit tests across different environments
  test-and-lint:
    name: Test on Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Run unit tests with pytest
        run: |
          pytest

  # Job 2: Build the Docker image to ensure it's not broken
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    # This job should run only after the primary tests have passed
    needs: test-and-lint 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          docker build -t portfolio-optimizer:latest .

      - name: Run a simple command in the container as a smoke test
        run: |
          docker run --rm portfolio-optimizer:latest python -c "import pandas; print('Pandas imported successfully')"